### PR TITLE
Add navigation directives

### PR DESCRIPTION
**Pull request by naotone**
Add "form-action" and "frame-ancestors" as Navigation directives.
Move "navigate-to" to Navigation directives from Reporting directives.

Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#navigation_directives

Thanks for developing this repo!
This pull request is included jest test codes, so It should be fine.
Btw, I hope I could read your blog posts this year! I enjoy it as an Apple信者.

### CODE REVIEW

**Comment by jagaapple** [comment]
@naotone 
Thank you for your pull request 😃, but I'm sorry, currently I don't have time to commit to this library.
I'll check and merge this pull request and release a new version in February 🙇🏻 

> Btw, I hope I could read your blog posts this year!

😂😂😂

**Comment by helfi92** [comment]
@jagaapple Any chance we could merge this PR? Thanks!

**Comment by naotone** [comment]
@jagaapple I missed your reply, sorry. Please let me know if you need help!

**Review by jagaapple — APPROVED** [review]
Looks good 🎉 
Thank you!

**Pull request merged**
