### PR TITLE
Add about frame-ancestors CSP directive to readme

### LINKED ISSUE #45: Support for frame-ancestors
# 🌱 Feature Request
## Is your feature request related to a problem? Please describe.
A clear and concise description of what you want and what your use case is.

I'm looking to set the CSP frame-ancestors header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

as such: 

```
Content-Security-Policy: frame-ancestors 'self' https://www.example.org;
```

## Describe the solution you'd like

I would like to be able to set in the configuration a key value such as...

```
frameAncestors: "'self' https://www.example.org"
```

## Describe alternatives you've considered
I'm currently doing this...

```
    headers: async () => [
      {
        source: '/(.*)',
        headers: [
          ...createSecureHeaders(),
          {
            key: 'Content-Security-Policy',
            value: "frame-ancestors 'self' *.example.com;",
          },
        ]
      },
    ],
```

## Documentation, Adoption, Migration Strategy
If you can, explain how users will be able to use this and how it might be documented. Maybe a mock-up?

## Additional context

---

- [ ] I've tried to find similar issues and pull requests
- [x] I would like to work on this feature 💪🏻

### PR DESCRIPTION
**Pull request by mattdell**
# New Features
- Add frame-ancestors to content security policy object in accordance with the Content Security Policy directives: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

# Changes and Fixes
- Modify content-security-policy.ts to accept `frameAncestors` or `frame-ancestors`
- Fixes #45

### CODE REVIEW

**Comment by mattdell** [comment]
Must say I don't see how the code coverage is going down so much as I've added tests...! 😅

**Comment by jagaapple** [comment]
Thank you for your pull request😃
I'm busy, so I'll review this within two weeks.

This feature will be merged in v2.2.0.

**Comment by mattdell** [comment]
That's great, @jagaapple 

I figured out the issue with code coverage. I had left a `.only` in the unit tests...! 🤦🏻‍♂️

I will also add some documentation to the README when I get a chance.

**Comment by helfi92** [comment]
Looking forward to this! 🎉

**Comment by jagaapple** [comment]
This PR is duplicated with #41 , but I will merge the README @mattdell edited about `X-Frame-Options` header.

Thank you!

**Pull request merged**
